dtl/urls.py
from django.contrib import admin
from django.urls import path, include
from todoapp import views
from todoapp import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', v.home),
    #path('abt/', v.about),
    #path('con/', v.contact),
    #path('pro/', v.product),
    path('', include(urls)),
]

todoapp/urls.py
from django.urls import path

from todoapp import views

urlpatterns = [
    
   
    #path('abt/', v.about),
    #path('con/', v.contact),
    #path('pro/', v.product),
    path("dashboard", views.dashboard),
    path('delete/<int:rid>', views.delete),
    path("edit/<int:rid>", views.edit),
    path("Mumbai/", views.mumbai),
    path("Delhi/", views.delhi),
    path("Bangalore/", views.bangalore),
]

todoapp/models.py
from django.db import models

class Company_Task(models.Model):
    title=models.CharField(max_length=50)
    detail=models.CharField(max_length=500)
    cat=models.CharField(max_length=10)
    date=models.DateField()
    is_deleted=models.CharField(max_length=5)

dtl/views.py
from django.shortcuts import render, HttpResponse

def home(request):
   # num=40
    #content = {}
    #content['data']=num
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def product(request):
    return render(request, 'product.html')

# def dashboard(request):
    if request.method=="POST":
        return HttpResponse("IN POST")
    else:
        return render(request,'dashboard.html')

todoapp/views.py
from django.shortcuts import render, HttpResponse, redirect
from todoapp.models import Company_Task

def delete(request, rid):
    t1=Company_Task.objects.get(id=rid)
    t1.delete()
    return redirect('/dashboard')

def edit(request, rid):
    if request.method=="POST":
        ut=request.POST['title']
        udet=request.POST['detail']
        ucat=request.POST['cat']
        udate=request.POST['date']

        t1=Company_Task.objects.filter(id=rid)
        t1.update(title=ut, detail=udet, cat=ucat, date=udate)
        return redirect('/dashboard')




    rec=Company_Task.objects.filter(id=rid)
    content={}
    content['data']=rec
    return render(request, 'editform.html', content)


def dashboard(request):
    if request.method=='POST':
        t=request.POST['title']
        det=request.POST['detail']
        cat=request.POST['cat']
        dt=request.POST['date']

        t1=Company_Task.objects.create(title=t, detail=det, cat=cat, date=dt, is_deleted='N')
        #inserrt into
        t1.save()
        return redirect('/dashboard')
        #return HttpResponse("IN POST")
    else:
        records=Company_Task.objects.all()
        content={'data':records}
        return render(request, 'dashboard.html', content)

def mumbai(request):
    records=Company_Task.objects.filter(detail="Mumbai")
    content={}
    content['data']=records
    return render(request, 'dashboard.html', content)

def delhi(request):
    records=Company_Task.objects.filter(detail="Delhi")
    content={}
    content['data']=records
    return render(request, 'dashboard.html', content)

def bangalore(request):
    records=Company_Task.objects.filter(detail="Bangalore")
    content={}
    content['data']=records
    return render(request, 'dashboard.html', content)

templates/about.html
{% extends 'base.html' %}

{% block 'main' %}
    <h1> This is about page </h1>
{% endblock 'main' %}

templates/base.html
{% include 'header.html' %}

{% block 'main' %}
  
{% endblock 'main' %}

{% include 'footer.html' %}

templates/contact.html
{% extends 'base.html' %}
    
{% block 'main' %}
    <h1> This is contact page </h1>
{% endblock 'main' %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block 'main' %}

<div class="col-md-4 mt-5">
    <form method="POST" action="dashboard">
        {% csrf_token %}
        <h3 class="bg bg-primary text-white text-center">To Do Form </h3>
        <div class="mb-3">
            <label for="id-title" class="form-label">Emp Name</label>
            <input type="text" name="title" class="form-control" id="id-title" placeholder="Enter Name">
        </div>
        <div class="mb-3">
            <label for="id_detail" class="form-label">Address Location</label>
            <input class="form-control" name="detail" id="id_detail" pllaceholder="Enter Location - Address">
        </div>
        <div class="mb-3">
            <select class="form-select" name="cat" aria-label="Default select example">
                <option selected>Open this select menu</option>
                <option value="P">Personal</option>
                <option value="O">Office</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="id_date" class="form-label">Date Of Joining</label>
            <input class="form-control" name="date" id="id_date" type="date">
        </div>
        <input type="submit" value="CREATE" class="btn btn-primary">
    </form>
    <h4> Filter by Address</h4>
    <hr>
    <p><a href="Mumbai">By Mumbai</a></p>
    <p><a href="Delhi">By Delhi</a></p>
    <p><a href="Bangalore">By Bangalore</a></p>
</div>

<div class="col-md-8 mt-5">
    <h3 class="bg bg-primary text-white text-center">TASK</h3>
        <table class="table table-hover table-hovered">
        <thead>
          <tr>
            <th scope="col">Emp Name</th>
            <th scope="col">Address</th>
            <th scope="col">Category</th>
            <th scope="col">Date Of Joining</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
       
        <tbody>
        {% for x in data %}
            <tr>
            <td>{{x.title}}</td>
            <td>{{x.detail}}</td>
            <td>{{x.cat}}</td>
            <td>{{x.date}}</td>
            <td><a href="edit/{{x.id}}"><button class="btn btn-primary"> Edit</button></a></td>
            <td><a href="delete/{{x.id}}"><button class="btn btn-danger"> Delete</button></a></td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
</div>


{% endblock 'main' %}

templates/editform.html
{% extends 'base.html' %}
{% load static %}
{% block 'main' %}

<div class="col-md-4 mt-5">
    {% for x in data %}
    <form method="POST" action="/edit/{{x.id}}">
        {% csrf_token %}
        <h3 class="bg bg-primary text-white text-center">To Do Form</h3>
        <div class="mb-3">
            <label for="id-title" class="form-label">Title</label>
            <input type="text" name="title" value="{{x.title}}"  class="form-control" id="id-title" placeholder="Enter Title">
        </div>
        <div class="mb-3">
            <label for="id_detail" class="form-label">Example Details</label>
            <textarea class="form-control" name="detail" id="id_detail" rows="3">{{x.detail}}</textarea>
        </div>
        <div class="mb-3">
            <select class="form-select" name="cat" aria-label="Default select example">
                <option selected>{{x.cat}}</option>
                <option value="P">Personal</option>
                <option value="O">Office</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="id_date" class="form-label">Date</label>
            <input class="form-control" value="{{x.date}}" name="date" id="id_date" type="date">
        </div>
        <input type="submit" value="UPDATE" class="btn btn-primary">
    </form>
    {% endfor %}
</div>




{% endblock 'main' %}

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body>
    </div>
   
</div>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'css/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <!-- Nav bar start-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">To Do App</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Registration</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                      </li>
                      <!--<li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                      </li> -->
                    </ul>
                  </div>
                </div>
              </nav>
            <!-- Nav bar end-->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block 'main' %}
    <h1> This is home page </h1>
    <button onclick="hello()">Click Me</button>
    <img src="{% static 'images/car.jpg' %}" alt="'car" height="400px" width="1000px">

{% endblock 'main' %}

templates/product.html
{% extends 'base.html' %}
 
{% block 'main' %}
    <h1> This is product page </h1>
{% endblock 'main' %}